import { shorthand } from 'marycat'
export const slot = shorthand('slot')
export const h1 = shorthand('h1')
export const div = shorthand('div')
export const img = shorthand('img')
export const pre = shorthand('pre')
export const span = shorthand('span')
export const main = shorthand('main')
export const iframe = shorthand('iframe')
export const button = shorthand('button')
export const header = shorthand('header')
export const article = shorthand('article')
export const section = shorthand('section')
export const form = shorthand('form')
export const input = shorthand('input')
export const textarea = shorthand('textarea')
