# Generated by Django 2.2.1 on 2019-08-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_comment_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='user_id',
            new_name='user',
        ),
    ]
