# Generated by Django 2.2.1 on 2019-09-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_course_lecture_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Lecture'),
        ),
    ]
