# Generated by Django 2.2.1 on 2019-09-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20190918_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='slide_id',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='for_article',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='slide_id',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='lecture_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Lecture'),
        ),
        migrations.AddField(
            model_name='comment',
            name='slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Slide'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='for_lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Lecture'),
        ),
        migrations.AddField(
            model_name='progress',
            name='slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Slide'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Lecture'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='for_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Exercise'),
        ),
    ]
